main:
	@echo "Compilando ficheros..."
	g++ -std=c++17 lattice.cc cell.cc main.cc -o juego_de_la_vida

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f juego_de_la_vida