main:
	@echo "Compilando ficheros..."
	g++ -g alfabeto.cc position.cc lattice.cc cell.cc state.cc main.cc -o automata_celular

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f automata_celular