main:
	@echo "Compilando ficheros..."
	g++ -std=c++17 -I src src/main.cc src/cell/cell.cc src/options/options.cc -o automata_celular_general
.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f automata_celular_general